version: "3.1"

services:
  postgres:
    image: "postgres:13"
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: group_challenge
    networks:
      - internal
  group-challenge:
    image: "local.test/group-challenge:latest"
    restart: always
    ports:
      - 8080:8080
    volumes:
      - "./config.yaml:/app/config.yaml"
    networks:
      - internal
    depends_on:
      - postgres

networks:
  internal:
