version: "3.9"

services:
  postgres:
    image: "postgres:14"
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: group_challenge
  imgProxy:
    image: "darthsim/imgproxy:v3.3.3"
    ports: 
      - 8081:8081
      - 8082:8082
    environment:
      IMGPROXY_LOCAL_FILESYSTEM_ROOT: /tmp/group-challenge-cache
      IMGPROXY_BIND: ":8081"
      IMGPROXY_PROMETHEUS_BIND: ":8082"
    volumes:
      - type: bind
        source: /tmp/group-challenge-cache
        target: /tmp/group-challenge-cache
