apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "group-challenge.fullname" . }}
  labels:
    {{- include "group-challenge.labels" . | nindent 4 }}
data:
  config.yaml: |- {{ toYaml (required "A valid config.yaml config is required (nested in the value .Values.groupChallenge.config)!" .Values.groupChallenge.config) | nindent 4 }}