{{- if .Values.serviceMonitor.enabled -}}
{{- $fullName := include "group-challenge.fullname" . -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    name: {{ $fullName }}
    labels: {{- include "group-challenge.labels" . | nindent 8 }}
spec:
    selector:
        matchLabels: {{- include "group-challenge.selectorLabels" . | nindent 12 }}
    endpoints:
        - interval: {{ .Values.serviceMonitor.interval }}
          port: http
          path: {{ .Values.serviceMonitor.path }}
        - interval: {{ .Values.serviceMonitor.interval }}
          port: http-imgproxy-prometheus
          path: /
{{- end }}
