apiVersion: v1
kind: Service
metadata:
  name: {{ include "group-challenge.fullname" . }}
  labels:
    {{- include "group-challenge.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{ if .Values.imgProxy.enabled -}}
    - port: 8082
      targetPort: http-imgproxy-prometheus
      protocol: TCP
      name: http-imgproxy-prometheus
    {{- end }}
  selector:
    {{- include "group-challenge.selectorLabels" . | nindent 4 }}
