server:
  port: 8080
  staticFilesDir: "./static"
db:
  user: postgres
  password: postgres
  database: group_challenge
  host: "localhost:5432"
  poolSize: 50
  logQueries: false
challenges:
  liveParty:
    defaultTimePerSubmissionSeconds: 45
  fileUpload:
    maxFileSizeMb: 5
imgProxy:
  enabled: true
  url: "http://localhost:8081"
  sharedLocalCacheDir: "/tmp/group-challenge-cache"
  thumbnailQuality: 90
  maxThumbnailWidth: 420
  maxThumbnailHeight: 420
  fullSizeQuality: 75
  maxFullWidth: 1280
  maxFullHeight: 1280
